version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/myproject
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
  celery:
    build: .
    restart: always  
    command: celery -A myproject worker -l info
    volumes:
      - ./myproject/:/usr/src/app/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A myproject beat -l info
    volumes:
      - ./myproject/:/usr/src/app/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
    depends_on:
      - redis
      - celery


